name: nwt-bot
dependencies:
  - python=3.11.3
  - pip
  - pip:
    - python-telegram-bot==13.15
    - SQLAlchemy<2.0
    - requests
    - Unidecode
    - mechanicalsoup
    - ruamel.yaml
    - numpy
    - Pillow
    - python-dotenv
